mod.id="traceableprint"
mod.name="Traceable Print"
mod.version="1.0.1"
mod.description="Added interactive footprints that allow you to track the mob that left them."
mod.author="Rimo"
mod.contributor="You"
mod.sources="https://github.com/Rivmun/TraceablePrint"
mod.issues="https://github.com/Rivmun/TraceablePrint/issues"
mod.homepage="https://www.curseforge.com/minecraft/mc-mods/traceable-print"
mod.modrinth="https://modrinth.com/mod/traceable-print"
mod.mcmod="https://www.mcmod.cn/class/31390.html"
mod.license="GPL-3.0-or-later"
mod.icon="icon.png"

["26.3-fabric"]
deps.minecraft="26.3"
version_range="~26.3"
deps.fabric="0.19.5"
deps.fabric-api="0.160.5+26.3"
deps.modmenu="21.0.0"
deps.cloth="26.3.159"

["26.3-neoforge"]
loom.platform="neoforge"
deps.minecraft="26.3"
version_range="[26.3,26.4)"
deps.neoforge="26.3.0.37-beta"
neoforge_min_version="26.3"
deps.cloth="26.3.159"

["26.2-fabric"]
deps.minecraft="26.2"
version_range="~26.2"
deps.fabric="0.19.2"
deps.fabric-api="0.150.0+26.2"
deps.modmenu="20.0.3"
deps.cloth="26.2.155"

["26.2-neoforge"]
loom.platform="neoforge"
deps.minecraft="26.2"
version_range="[26.2,26.3)"
deps.neoforge="26.2.0.88"
neoforge_min_version="26.2"
deps.cloth="26.2.155"

["26.1-fabric"]
deps.minecraft="26.1.2"
version_range="~26.1"
deps.fabric="0.19.2"
deps.fabric-api="0.146.1+26.1.2"
deps.modmenu="18.0.0"
deps.cloth="26.1.154"

["26.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="26.1.2"
version_range="[26.1,26.2)"
deps.neoforge="26.1.2.75"
neoforge_min_version="26.1"
deps.cloth="26.1.154"

["1.21.11-fabric"]
deps.minecraft="1.21.11"
version_range="=1.21.11"
deps.fabric="0.18.4"
deps.fabric-api="0.141.3+1.21.11"
deps.modmenu="17.0.0"
deps.cloth="21.11.153"

["1.21.11-neoforge"]
loom.platform="neoforge"
deps.minecraft="1.21.11"
version_range="[1.21.11]"
deps.neoforge="21.11.42"
neoforge_min_version="21.11"
deps.cloth="21.11.153"

["1.21.1-fabric"]
deps.minecraft="1.21.1"
version_range="=1.21.1"
deps.fabric="0.18.4"
deps.fabric-api="0.116.9+1.21.1"
deps.modmenu="11.0.1"
deps.cloth="15.0.140"

["1.21.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="1.21.1"
version_range="[1.21.1]"
deps.neoforge="21.1.219"
neoforge_min_version="21.1"
deps.cloth="15.0.140"

["1.20.1-fabric"]
deps.minecraft="1.20.1"
version_range=">=1.20 <=1.20.1"
deps.fabric="0.17.1"
deps.fabric-api="0.92.6+1.20.1"
deps.modmenu="7.0.0"
deps.cloth="11.1.136"

["1.20.1-forge"]
loom.platform="forge"
deps.minecraft="1.20.1"
version_range="[1.20,1.20.1]"
deps.forge="1.20.1-47.1.0"
forge_min_version="46"
deps.mixinextras="0.5.0"
deps.cloth="11.1.136"
