mod.id="traceableprint"
mod.name="Traceable Print"
mod.version="1.0.0"
mod.description="Add interactable footprint for mob that can tracing where they move to the Minecraft."
mod.author="Rimo"
mod.contributor="You"
mod.sources="https://github.com/Rivmun/TraceablePrint"
mod.issues="https://github.com/Rivmun/TraceablePrint/issues"
mod.homepage="https://www.curseforge.com/minecraft/mc-mods/superfancyclouds-refabricated"
mod.modrinth="https://modrinth.com/mod/superfancyclouds-refabricated"
mod.mcmod="https://www.mcmod.cn/class/9053.html"
mod.license="GPL-3.0-or-later"
mod.icon="icon.png"

["26.1-fabric"]
deps.minecraft="26.1.2"
version_range="~26.1"
deps.fabric="0.19.2"
deps.fabric-api="0.146.1+26.1.2"
deps.modmenu="18.0.0"
deps.cloth="26.1.154"

["26.1-neoforge"]
loom.platform="neoforge"
deps.minecraft="26.1.2"
version_range="[26.1,)"
deps.neoforge="26.1.2.75"
neoforge_min_version="26.1"
deps.cloth="26.1.154"

["1.20.1-forge"]
loom.platform="forge"
deps.minecraft="1.20.1"
version_range="[1.20,1.20.1]"
deps.forge="1.20.1-47.1.0"
forge_min_version="46"
deps.mixinextras="0.5.0"
deps.cloth="11.1.136"
